sudo: required
services: 
  - docker

before_install: 
  - docker build -t pbernard/fibonacci-app -f ./client/Dockerfile.dev ./client

script: 
  - docker run pbernard/fibonacci-app npm run test -- --coverage

after_success:
  - docker build -t pbernard/fibonacci-app-client ./client
  - docker build -t pbernard/fibonacci-app-nginx ./nginx
  - docker build -t pbernard/fibonacci-app-server ./server
  - docker build -t pbernard/fibonacci-app-worker ./worker

# log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take the images and push to the docker hub.
  - docker push pbernard/fibonacci-app-client
  - docker push pbernard/fibonacci-app-nginx
  - docker push pbernard/fibonacci-app-server
  - docker push pbernard/fibonacci-app-worker

