sudo: required
services: 
  - docker

before_install: 
  - docker build -t pbernard/fibonacci-app -f ./client/Dockerfile.dev .

script: 
  - docker run pbernard/fibonacci-app npm run test -- --coverage